[package]
name = "rusticus_buy_books"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.31.0"
egui = "0.28.0"
eframe = "0.28.0"
env_logger = "0.11.3"
chrono = "0.4"